test = {   'name': 'q2_1',
    'points': None,
    'suites': [   {   'cases': [   {'code': '>>> len(cum_income_share)\n5', 'hidden': False, 'locked': False},
                                   {'code': '>>> np.sum(np.diff(cum_income_share) >= 0) == 4\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> np.isclose(sum(us_cumulative.column("income_percentile")), 3.0)\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> np.isclose(sum(us_cumulative.column("cum_income_share")), 1.881)\nTrue', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
